### PR TITLE
use at least one paragraph on each JLBP, not just lists

### PR DESCRIPTION
**Pull request by elharo**
@garrettjonesgoogle I also added blank lines between list items to make Kramdown (part of Jekyll/github pages include p elements inside its li elements.) That is, this is going to turn a lot of

```
<ul>
<li>Lorem ipsum</li>
</ul>
```

into 

```
<ul>
<li><p>Lorem ipsum</p></li>
</ul>
```

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
This... doesn't seem standard. Why does it need to be done?

**Comment by elharo** [comment]
This adds whitespace between list items. Otherwise they appear cramped and less readable. It also makes list items that contain more than one paragraph consistent with those that contain only a single paragraph.

**Comment by garrettjonesgoogle** [comment]
@elharo it's something I've only see you do. @suztomo What are your thoughts?

**Comment by suztomo** [comment]
CSS should control the visual margin between list items, not Markdown. Therefore we should not add unnecessary spaces between list items in Markdown.

**Comment by elharo** [comment]
See https://googlecloudplatform.github.io/cloud-opensource-java/JLBP-2.html which is pre this PR. Having only a list on the page feels much stranger in rendered HTML than in markdown.

Re, paragraphs in list items this is allowed and accepted in HTML. If each list item is a paragraph, generally a complete sentence or more, then I expect `<p>` elements to be used. If, on the other hand, each list item is just a word or two, then I don't expect `<p>`.

In our case there are a few places where we are already using two or more paragraphs in a single list item. That suggests the rest of these should be paragraphs too.

**Pull request closed without merging**
