### PR TITLE
chore: LTS 5 versions

### PR DESCRIPTION
**Pull request by burkedavison**

### CODE REVIEW

**Comment by burkedavison** [comment]
I'm surprised this is passing. Locally, I get the following error:
```
[ERROR] Tests run: 22, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.888 s <<< FAILURE! - in com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilderTest
[ERROR] testSetDetectedOsSystemProperties_netty4Dependency(com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilderTest)  Time elapsed: 0.228 s  <<< FAILURE!
com.google.common.truth.AssertionErrorWithFacts: 
value of: getUnresolvedArtifacts()
expected to be empty
but was : [io.netty:netty-tcnative:jar:osx-x86_32:2.0.19.Final was not resolved. Dependency path: io.netty:netty-all:jar:4.1.31.Final (compile) > io.netty:netty-example:jar:4.1.31.Final (compile?) > io.netty:netty-tcnative:jar:osx-x86_32:2.0.19.Final (compile?), io.netty:netty-transport-native-kqueue:jar:osx-x86_32:4.1.31.Final was not resolved. Dependency path: io.netty:netty-all:jar:4.1.31.Final (compile) > io.netty:netty-transport-native-kqueue:jar:osx-x86_32:4.1.31.Final (compile?)]
        at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilderTest.testSetDetectedOsSystemProperties_netty4Dependency(DependencyGraphBuilderTest.java:296)
```

**Comment by suztomo** [comment]
It seems Mac specific error.

**Comment by suztomo** [comment]
Nice nice if it can be solved. But the BOM doesn't get affected by Mac. I marked the check non-required.

**Comment by burkedavison** [comment]
Display name in pull request | Command in pull request comments | Gradle goals | Success?
-- | -- | -- | --
Java SDK Post Commit Tests | Run Java Postcommit | :sdks:java:io:google-cloud-platform:postCommit | [Yes](https://ci-beam.apache.org/job/beam_PostCommit_Java_PR/1171/)
Java_PVR_Flink_Batch | Run Java_PVR_Flink_Batch PreCommit | :runners:flink:1.13:job-server:validatesPortableRunnerBatch | [Yes](https://ci-beam.apache.org/job/beam_PreCommit_Java_PVR_Flink_Batch_Phrase/79/)
Java Spark PortableValidatesRunner Batch Tests | Run Java Spark PortableValidatesRunner Batch | :runners:spark:2:job-server:validatesPortableRunnerBatch, :runners:spark:3:job-server:validatesPortableRunnerBatch | ?
Dataflow V2 Java Post Commit Tests | Run PostCommit_Java_DataflowV2 | :runners:google-cloud-dataflow-java:validatesRunnerV2 | [Yes](https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV2_PR/203/)
Google Cloud Dataflow Runner V2 Java ValidatesRunner Tests | Run Java Dataflow V2 ValidatesRunner Streaming | :runners:google-cloud-dataflow-java:validatesRunnerV2Streaming | [Yes](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming_PR/101/)

**Review by suztomo — APPROVED** [review]

**Pull request merged**
