### PR TITLE
Bom 2.5.0

### PR DESCRIPTION
**Pull request by elharo**
@suztomo Is the script supposed to update the version number in pom.xml?

### CODE REVIEW

**Comment by suztomo** [comment]
Yes, it is supposed to increment patch version when next version is omitted. I might introduce a bug when I updated it to take additional argument.

**Comment by elharo** [comment]
Or when the next version isn't omitted. The command I ran was

../../scripts/prepare_release.sh bom 2.5.0 2.6.0

**Comment by elharo** [comment]
Yes, that's it. It works unless you specify the new version. 

https://github.com/GoogleCloudPlatform/cloud-opensource-java/compare/bom-2.6.0

**Comment by elharo** [comment]
I think

```
if [ -n "$3" ]; then
  NEXT_VERSION=$2
  CheckVersion ${NEXT_VERSION}
```

should perhaps be

```
if [ -n "$3" ]; then
  NEXT_VERSION=$3
  CheckVersion ${NEXT_VERSION}
```

**Pull request closed without merging**
