### PR TITLE
Removing httpclient dependencies throws exception

### PR DESCRIPTION
**Pull request by suztomo**
```
Exception in thread "DefaultMetadataResolver-0-1" Exception in thread "DefaultMetadataResolver-0-0" java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.aether.transport.http.SslSocketFactory
	at org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:177)
	at org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:63)
	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:137)
	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:71)
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:104)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:129)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:155)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:107)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:570)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.aether.transport.http.SslSocketFactory
	at org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:177)
	at org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:63)
	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:137)
	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:71)
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:104)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:129)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:155)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:107)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:570)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### CODE REVIEW

**Comment by suztomo** [comment]
The artifact is a transitive dependency of https://search.maven.org/artifact/org.apache.maven.resolver/maven-resolver-transport-http/1.6.1/jar, which this module depends on.

```
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.12</version>
      <exclusions>
        <exclusion>
          <!-- using jcl-over-slf4j instead -->
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

# Dependency Tree

Before the removal: https://gist.github.com/suztomo/af210f8c30ac8dd6fba2a979140379ef

```
[INFO] +- org.apache.maven.resolver:maven-resolver-transport-http:jar:1.6.1:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.12:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] |  \- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] +- org.apache.maven.resolver:maven-resolver-transport-file:jar:1.6.1:compile
[INFO] +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.1:compile
```


After the removal: https://gist.github.com/suztomo/bf3b48504986b7ae417cd3b15941ae7f


```
[INFO] +- org.apache.maven.resolver:maven-resolver-transport-http:jar:1.6.1:compile
[INFO] |  \- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] +- org.apache.maven.resolver:maven-resolver-transport-file:jar:1.6.1:compile
[INFO] +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.1:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.12:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.11:compile
```

**Comment by suztomo** [comment]
This is suspicious static initializers for `Could not initialize class org.eclipse.aether.transport.http.SslSocketFactory`:

```
  public static final X509HostnameVerifier ALLOW_ALL_HOSTNAME_VERIFIER = new AllowAllHostnameVerifier();
  public static final X509HostnameVerifier BROWSER_COMPATIBLE_HOSTNAME_VERIFIER = new BrowserCompatHostnameVerifier();
  public static final X509HostnameVerifier STRICT_HOSTNAME_VERIFIER = new StrictHostnameVerifier();
```

org.apache.http.conn.ssl.SSLSocketFactory

**Comment by elharo** [comment]
What's the problem here? Why remove this at all?

**Comment by suztomo** [comment]
@elharo I found the artifact `org.apache.httpcomponents:httpclient` is unused in this project. But the test fails if I remove it. I wonder why we need to declare this dependency at "dependencies" module.

Do you know why we need the artifact?

**Comment by suztomo** [comment]
It seems that it's `commons-logging`, a dependency of `org.apache.httpcomponents:httpclient`, that is required by maven-resolver-transport-http. maven-resolver-transport-http excludes it saying "using jcl-over-slf4j instead".

**Pull request closed without merging**
