### PR TITLE
Release 13.0.0-bom

### PR DESCRIPTION
**Pull request by elharo**
Release 13.0.0-bom

### CODE REVIEW

**Comment by elharo** [comment]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.google.cloud:libraries-bom:pom:13.0.0-SNAPSHOT @ line 43, column 19
[ERROR] 'dependencies.dependency.version' for com.google.cloud:google-cloud-core:jar is missing. @ line 57, column 17
[ERROR] 'dependencies.dependency.version' for com.google.cloud:google-cloud-storage:jar is missing. @ line 61, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.google.cloud:libraries-bom:pom:13.0.0-SNAPSHOT @ line 43, column 19
[ERROR] 'dependencies.dependency.version' for com.google.cloud:google-cloud-core:jar is missing. @ line 57, column 17
[ERROR] 'dependencies.dependency.version' for com.google.cloud:google-cloud-storage:jar is missing. @ line 61, column 17

    at org.apache.maven.project.DefaultProjectBuilder.

**Comment by elharo** [comment]
for some reason the release script did not update boms/upper-bounds-check/pom.xml

**Comment by elharo** [comment]
This changed in https://github.com/mojohaus/versions-maven-plugin/pull/400

not a result of the new script. temporarily we can pin the previous version.

**Comment by suztomo** [comment]
I don't remember we upgraded the version of Maven since the last release of the libraries BOM.

**Pull request closed without merging**
