### PR TITLE
demonstrate missing dependencies in appengine-api-1.0-sdk

### PR DESCRIPTION
**Pull request by elharo**
@ludoch 

The pom.xml for com.google.appengine:appengine-api-1.0-sdk:1.9.71 does not declare its own dependencies as this example demonstrates. 

```
elharo-macbookair99:appengineapisdkexample elharo$ mvn exec:java
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building appengineapisdkexample 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ appengineapisdkexample ---
[WARNING] 
java.lang.NoClassDefFoundError: com/google/net/rpc3/client/RpcStubCreationFilter
	at com.google.cloud.tools.examples.AppEngineApiSdkExample.main(AppEngineApiSdkExample.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.net.rpc3.client.RpcStubCreationFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.166 s
[INFO] Finished at: 2019-01-31T15:55:53-05:00
[INFO] Final Memory: 7M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project appengineapisdkexample: An exception occured while executing the Java class. com/google/net/rpc3/client/RpcStubCreationFilter: com.google.net.rpc3.client.RpcStubCreationFilter -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### CODE REVIEW

**Comment by suztomo** [comment]
Nice valid example. Would you add README.md with the description of this PR (excluding `@ludoch` in the first line)?

**Comment by patflynn** [comment]
@elharo did you try running it on appengine?  It may be provided.

**Comment by elharo** [comment]
I'll try that and see what happens, but even if it works on App Engine the issue still stands. The jar references classes it neither includes nor lists a dependency on, provided or otherwise.

**Comment by elharo** [comment]
similar test fails when running in the dev_appserver:

```
HTTP ERROR 500

Problem accessing /hello. Reason:

    Server Error
Caused by:

java.lang.NoClassDefFoundError: com/google/net/rpc3/client/RpcStubCreationFilter
	at com.google.cloud.tools.examples.HelloAppEngine.doGet(HelloAppEngine.java:27)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:134)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.tools.development.jetty9.StaticFileFilter.doFilter(StaticFileFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.appengine.tools.development.DevAppServerRequestLogFilter.doFilter(DevAppServerRequestLogFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:601)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.net.rpc3.client.RpcStubCreationFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:239)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
```

**Comment by elharo** [comment]
Weirder and weirder. This was all in Eclipse but at the command line it fails to compile to a missing javax.inject.Provider class that isn't referenced:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project linkfailurexample: Compilation failure
[ERROR] /Users/elharo/workspaces/cloud-opensource-java/linkfailurexample/src/main/java/com/google/cloud/tools/examples/HelloAppEngine.java:[27,15] cannot access javax.inject.Provider
[ERROR]   class file for javax.inject.Provider not found
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
elharo-macbookair99:linkfailurexample elharo$ more /Users/elharo/workspaces/cloud-opensource-java/linkfailurexample/src/main/java/com/google/cloud/tools/examples/HelloAppEngine.java
package com.google.cloud.tools.examples;

import java.io.IOException;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.google.protos.cloud.sql.SqlService.ServerInterface;
import com.google.protos.cloud.sql.SqlService;

@WebServlet(
    name = "HelloAppEngine",
    urlPatterns = {"/hello"}
)
public class HelloAppEngine extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {

    response.setContentType("text/plain");
    response.setCharacterEncoding("UTF-8");
    
    ServerInterface impl = null;
    SqlService.newService(impl);

    response.getWriter().print("Hello App Engine!\r\n");

  }
}
```

**Comment by suztomo** [comment]
I was able to reproduce the issue and resolved by importing `javax.inject` package:

```
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
      <version>1</version>
    </dependency>
```

SqlService class uses `javax.inject.Provider` class. The class is available until JDK 7 ([javadoc](https://docs.oracle.com/javaee/7/api/javax/inject/Provider.html)), but not in JDK8. Normally javac does not check the validity of import statement of already-compiled class file (SqlService class). However this case javac complains missing `javax.inject.Provider` in the class. Why Java compiler complains?

I think the answer is because javax.inject package is treated special in JDK to support "JSR 330: Dependency Injection for Java" at _compilation time_. The JSR says:

>  the injector can verify that all dependencies have been satisfied at build time.
https://jcp.org/en/jsr/detail?id=330

At the compilation time the OpenJDK tried to process the dependency injection for `SqlService` class, but it could not find `javax.inject.Provider` class because the class is no longer available in JDK8.

**Comment by elharo** [comment]
Huh, I didn't know anything like that had been removed from Java 7 --> Java 8. 
That's a separate and valid issue with com.google.appengine:appengine-api-1.0-sdk:1.9.71 then.

**Comment by suztomo** [comment]
Would you
- add one line in readme of example-projects?
https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/dependencies/example-projects/README.md
- rename the directory to "appengine-api-sdk-missing-dependency"
  (added missing-dependency to describe the problem and, as it's already under example-projects, no need to repeat "example")
?

**Pull request merged**
