### PR TITLE
deps: update google-http-client to 1.37.0

### PR DESCRIPTION
**Pull request by chingor13**
The next version of google-cloud-storage declares google-http-client 1.37.0

https://github.com/googleapis/java-cloud-bom/pull/1074

### CODE REVIEW

**Comment by elharo** [comment]
don't think you can upgrade this one in isolation:

Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.fasterxml.jackson.core:jackson-core:2.11.1 paths to dependency are:
+-com.google.cloud.tools.opensource:upper-bounds-check:2.0.0-SNAPSHOT
  +-com.google.cloud:google-cloud-storage:1.113.1
    +-com.fasterxml.jackson.core:jackson-core:2.11.1
and
+-com.google.cloud.tools.opensource:upper-bounds-check:2.0.0-SNAPSHOT
  +-com.google.cloud:google-cloud-core:1.93.9
    +-com.google.http-client:google-http-client-jackson2:1.37.0
      +-com.fasterxml.jackson.core:jackson-core:2.11.3

**Comment by chingor13** [comment]
So we can't update google-cloud-storage which is causing that in google-cloud-bom without google-http-client 1.37.0 in libraries-bom

**Review by elharo — COMMENTED** [review]
I think you'll need to add an explicit java-storage dependency here to override the one from google-cloud-bom.

**Comment by suztomo** [comment]
> an explicit java-storage dependency here

@elharo Which file are you suggesting updating?

**Comment by elharo** [comment]
Try adding an explicit dependency on google-cloud-storage to this pom.xml file, instead of just importing google-cloud-bom. I think that should override the version  we import from google-cloud-bom.

**Comment by elharo** [comment]
seems GAX is way behind and causing problems. We should update all its dependencies and release it.

**Comment by elharo** [comment]
we also need a new google-cloud-core release

**Review by elharo — COMMENTED** [review]
Here's what I've figured out so far:

1. GAX needs many updates and a release.
1.5 Possible shared dependencies needs the the new GAX in which case it needs a release. 
2. google-cloud-core needs a release
3. There needs to be a new google-cloud-bom that includes all of these.
4. libraries-bom needs to update GAX, http-client, auth-client, and google-cloud-bom at the same time.

These are necessary conditions. I'm not 100% sure they're sufficient. I suggest blocking out some time for the two of us to pair to send PRs, review, and release so we don't have to wait for day+ reviews.

**Comment by elharo** [comment]
The root cause is that several libraries have not been keeping up to date with dependencies and gotten behind. I'd really like to take a stab at fixing these.

**Comment by elharo** [comment]
I think flattening is confusing matters, at least for me, because what's published on Maven central is not what I see in the repos. It's giving some dependencies more weight than they should have.

**Comment by elharo** [comment]
closing in favor of #1771 but we are going to need to make some of these updates in GAX et al

**Pull request closed without merging**
