### PR TITLE
remove jcenter

### LINKED ISSUE #1980: Remove bintray dependency
It failed (temporarily?) today but we'll need to stop using jcenter.

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.apache.maven:maven-model:3.0.4.
     Required by:
         project : > com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin:0.12.0 > com.gradle.publish:plugin-publish-plugin:0.12.0
      > Could not resolve org.apache.maven:maven-model:3.0.4.
         > Could not get resource 'https://plugins.gradle.org/m2/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.pom'.
               > Read timed out
```

### PR DESCRIPTION
**Pull request by elharo**
fixes #1980 @suztomo

### CODE REVIEW

**Comment by suztomo** [comment]
I see it failed with a strange error on guice used by maven-core

```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.google.inject:guice:4.2.1.
     Searched in the following locations:
       - file:/home/runner/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
1 actionable task: 1 executed
     Required by:
         project : > com.google.cloud.tools:dependencies:1.5.8-SNAPSHOT > org.apache.maven:maven-core:3.6.3

```

**Comment by elharo** [comment]
Strange. It passed locally. Investigating...

**Comment by elharo** [comment]
```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.google.inject:guice:4.2.1.
     Searched in the following locations:
       - file:/home/runner/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
1 actionable task: 1 executed
         project : > com.google.cloud.tools:dependencies:1.5.8-SNAPSHOT > org.apache.maven:maven-core:3.6.3
```

**Comment by elharo** [comment]
same error on kokoro. https://repo1.maven.org/maven2/com/google/inject/guice/4.2.1/guice-4.2.1.pom exists

**Review by elharo — COMMENTED** [review]
PTAL

**Comment by suztomo** [comment]
I think it needs both maven local (to get snapshot) and maven central. Let's see the build.

**Comment by suztomo** [comment]
It needs mavenLocal (1.5.8-SNAPSHOT is only available in the local Maven repository).

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.google.cloud.tools:dependencies:1.5.8-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/cloud/tools/dependencies/1.5.8-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/google/cloud/tools/dependencies/1.5.8-SNAPSHOT/dependencies-1.5.8-SNAPSHOT.pom
```

The snapshot artifact is installed just before the Gradle build in https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/.github/workflows/ci.yaml#L20

**Review by suztomo — APPROVED** [review]

**Pull request merged**
