### PR TITLE
Added "view on GitHub" link

### LINKED ISSUE #926: JLBP template to have a link to this GitHub repository
From Ray:

> From the site, can we add a link back to GitHub?  Something like View on GitHub or Edit on GitHub would be awesome.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #926 . "View on GitHub" at the footer:

image

### CODE REVIEW

**Comment by suztomo** [comment]
Example: https://aip.dev/
Counter example: https://google.github.io/styleguide/javaguide.html, https://guava.dev/

@saturnism Would you share the background on this idea? I think of "Contact information".

**Comment by saturnism** [comment]
@elharo it's pretty standard practice. If I send / share this link, it's reasonable for users to be able to find the source, comment, discuss, send patches.  Often there is an "Edit on GitHub" or "Contribute on GitHub" link.

I don't feel "keep the website simple" is a reason not having this.

The counter examples should add link back to the source too if the source of truth was in fact open sourced.

**Comment by saturnism** [comment]
here is another example: https://12factor.net

**Comment by saturnism** [comment]
circling back to this - can we pls merge this :) i've been doing some talks around this. i'm constantly showing _both_ URLs on slides. JLBP.dev is much easier to remember and should link to the source for discussion.

**Comment by suztomo** [comment]
As per today's discussion, Elliotte still has not been convinced on this.

My points to promote "view on GitHub" link:
- Contact information on maintainers of jlbp.dev and on feedback for typos or inconsistencies.
  Better than searching the document title in Google search, because there's no guarantee that this GitHub repo comes at the top in the search result.
- Authority that "jlbp.dev" is maintained by GoogleCloudPlatform.

Elliotte's points:
- Not expecting external contribution because it's Google's practices.
- Concern on adding information not relevant to the content itself
  Example https://cloud.google.com/storage/docs/quickstart-console having the header, footer, and the left menu. All of them are irrelevant to the content.
- There might be better approach (such as email address) for contact information.
- @saturnism only needs "jlbp.dev" in slides.

**Comment by garrettjonesgoogle** [comment]
More points for adding the link:

* Precedent: aip.dev includes the links, and it is the same type of site - practices used by Google. 
* If our practices are useful, why not increase their impact by encouraging non-Google libraries to use them?
* The purpose of the github link isn't for contacting, it is for fixes / improvements.

**Pull request merged**
