### PR TITLE
test the LTS BOM

### LINKED ISSUE #2031: Verify LTS BOM
automated tests:

1. well-formed
2. valid pom.xml BOM
3. artifacts exist

### PR DESCRIPTION
**Pull request by elharo**
@suztomo fixes #2031

### CODE REVIEW

**Review by suztomo — APPROVED** [review]
Did you try putting an invalid artifact in the BOM?

**Comment by elharo** [comment]
Yes, it failed as expected:

```
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.google.cloud:libraries-bom:20.1.1-SNAPSHOT (/Users/elharo/cloud-opensource-java/boms/cloud-oss-bom/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not find artifact com.google.cloud:google-cloud-bom:pom:0.154.0 in central (https://repo.maven.apache.org/maven2) @ line 208, column 19 -> [Help 2]
[ERROR]   
[ERROR]   The project com.google.cloud.tools.opensource:upper-bounds-check:2.0.0-SNAPSHOT (/Users/elharo/cloud-opensource-java/boms/upper-bounds-check/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Failure to find com.google.cloud:google-cloud-bom:pom:0.154.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ com.google.cloud:libraries-bom:20.1.1-SNAPSHOT, /Users/elharo/cloud-opensource-java/boms/cloud-oss-bom/pom.xml, line 208, column 19 -> [Help 2]
```

**Comment by suztomo** [comment]
Nice. Thanks.

**Comment by suztomo** [comment]
The failure seems to come from the upper-bounds check. Can you try modifying gcp-lts-bom?

**Comment by elharo** [comment]
updated

**Comment by suztomo** [comment]
Great.

**Review by suztomo — APPROVED** [review]

**Pull request merged**
