### PR TITLE
Preparing BOM v1.0.0 release

### PR DESCRIPTION
**Pull request by suztomo**
Previous v1.0.0 tag had the old artifact ID [cloud-oss-bom](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/1.0.0/boms/cloud-oss-bom/pom.xml#L9). This PR is to set a new 1.0.0 that uses new artifact ID "libraries-bom".

### CODE REVIEW

**Comment by suztomo** [comment]
@garrettjonesgoogle Would you check this?.

**Comment by suztomo** [comment]
This auto-generated PR has two roles:
- Commit with non snapshot version with a tag
- Another commit to increment version number with “-SNAPSHOT”.

The latter needs to be merged.

Having said that, I found the group ID is not allowed to my team’s account.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/605

Closing this for now.

**Comment by suztomo** [comment]
Reopening this as #605 has been resolved and the artifact is in staging directory https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/601#issuecomment-493639385

**Comment by suztomo** [comment]
I think as long as it's not 1.0.0 it's just fine, because, we decide the exact version number when we release (run prepare_release.sh) next time.
Do you have a preference over 1.1.0?

**Comment by garrettjonesgoogle** [comment]
1.0.1 seems good - there will be no meaningful difference, we are just trying to sort out release issues.

**Comment by suztomo** [comment]
@elharo merged, keeping 1.1.0-SNAPSHOT. PTAL.

**Pull request closed without merging**
