### PR TITLE
use paragraphs for top level items, not lists JLBP-2

### PR DESCRIPTION
**Pull request by elharo**
@garrettjonesgoogle as discussed in meeting

### CODE REVIEW

**Comment by elharo** [comment]
Look at https://jlbp.dev/JLBP-2.html for the current HTML version. This one looks a little strange to me.  What do you think?

**Comment by garrettjonesgoogle** [comment]
The current HTML version seems fine (ish)...

**Comment by elharo** [comment]
Again https://g3doc.corp.google.com/company/engedu/writing/lists-and-tables.md?cl=head would suggest using paragraphs here. We shouldn't be opening with a list item.

**Comment by garrettjonesgoogle** [comment]
It just suggests opening with at least an introductory sentence that isn't a list item. That could be added before the existing list.

**Pull request merged**
