### PR TITLE
google-cloud-bom 0.148.0

### PR DESCRIPTION
**Pull request by suztomo**
I forgot to update the google-cloud-bom version before releasing 17.0.0.

### CODE REVIEW

**Review by chingor13 — COMMENTED** [review]
Are those 2 empty files intentional?

**Comment by suztomo** [comment]
@chingor13 No, Let me remove them.

**Review by chingor13 — APPROVED** [review]

**Review by elharo — COMMENTED** [review]
probably 17.1? or is it 18.0 if this is the first time we picked up spanner 4.0?

**Comment by suztomo** [comment]
I'll make a release for "18.0.0".
(Last time I made the same mistake for a major version upgrade, we bumped the major version)

**Pull request merged**
