### PR TITLE
Fix the dependency conflict issue #559

### PR DESCRIPTION
**Pull request by HelloCoCooo**

### CODE REVIEW

**Comment by HelloCoCooo** [comment]
@elharo 

google

Thanks for your reply.
As shown in the dependency tree, **_org.apache.httpcomponents:httpclient:jar:4.5.6_** expects to invoke the method **_<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>_** defined in the shadowed library **_commons-logging:commons-logging:1.2_** via expected dependency path.

However, the unexpected method with the same signature(i.e., method name ,reture type, parameter type) included in first declared library **_org.slf4j:jcl-over-slf4j:jar:1.7.25_** is forced to be referenced via the following forced dependency path:
```
<com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder: java.util.List getDirectDependencies(org.eclipse.aether.artifact.Artifact)> D:\testcase\TestProject\cloud-opensource-java-master\dependencies\target\classes
<com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder: org.eclipse.aether.graph.DependencyNode resolveCompileTimeDependencies(org.eclipse.aether.artifact.Artifact)> D:\testcase\TestProject\cloud-opensource-java-master\dependencies\target\classes
<org.eclipse.aether.internal.impl.DefaultRepositorySystem: org.eclipse.aether.resolution.DependencyResult resolveDependencies(org.eclipse.aether.RepositorySystemSession,org.eclipse.aether.resolution.DependencyRequest)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-impl\1.1.1\maven-resolver-impl-1.1.1.jar
<org.eclipse.aether.internal.impl.DefaultArtifactResolver: java.util.List resolveArtifacts(org.eclipse.aether.RepositorySystemSession,java.util.Collection)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-impl\1.1.1\maven-resolver-impl-1.1.1.jar
<org.eclipse.aether.internal.impl.DefaultArtifactResolver: java.util.List resolve(org.eclipse.aether.RepositorySystemSession,java.util.Collection)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-impl\1.1.1\maven-resolver-impl-1.1.1.jar
<org.eclipse.aether.internal.impl.DefaultArtifactResolver: void performDownloads(org.eclipse.aether.RepositorySystemSession,org.eclipse.aether.internal.impl.DefaultArtifactResolver$ResolutionGroup)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-impl\1.1.1\maven-resolver-impl-1.1.1.jar
<org.eclipse.aether.connector.basic.BasicRepositoryConnector: void get(java.util.Collection,java.util.Collection)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-connector-basic\1.3.1\maven-resolver-connector-basic-1.3.1.jar
<org.apache.http.impl.bootstrap.Worker: void run()> D:\cEnvironment\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar
<org.apache.http.protocol.HttpService: void handleRequest(org.apache.http.HttpServerConnection,org.apache.http.protocol.HttpContext)> D:\cEnvironment\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar
<org.apache.http.protocol.BasicHttpProcessor: void process(org.apache.http.HttpResponse,org.apache.http.protocol.HttpContext)> D:\cEnvironment\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar
<org.apache.http.client.protocol.ResponseAuthCache: void process(org.apache.http.HttpResponse,org.apache.http.protocol.HttpContext)> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient\4.5.6\httpclient-4.5.6.jar
<org.apache.http.impl.client.BasicAuthCache: void <init>()> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient\4.5.6\httpclient-4.5.6.jar
<org.apache.http.impl.client.BasicAuthCache: void <init>(org.apache.http.conn.SchemePortResolver)> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient\4.5.6\httpclient-4.5.6.jar
<org.apache.commons.logging.LogFactory: org.apache.commons.logging.Log getLog(java.lang.Class)> 
<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>

```

These two methods in the conflicting classes have different implementations, which changes the semantic behaviors of **_cloud-opensource-java_** along the forced dependency path (with different invocation contexts).

**Comment by HelloCoCooo** [comment]
As **_org.slf4j:jcl-over-slf4j:jar:1.7.25_** and **_commons-logging:commons-logging:1.2_** are transitively introduced by **_org.apache.maven.resolver:maven-resolver-transport-http:jar:1.3.3:compile_** and **_org.apache.httpcomponents:httpclient:jar:4.5.6:compile_**, respectively in **_cloud-opensource-java_**, so that reverse the declaration order of the above direct dependencies can workaround this issue.

Note that by static analysis, library **_org.apache.maven.resolver:maven-resolver-transport-http:jar:1.3.3:compile_** does not reference any methods defined the conflicting class **_org.apache.commons.logging.LogFactory_** belonging to **_org.slf4j:jcl-over-slf4j:jar:1.7.25_**. This fix will not affect other libraries or class, except the above duplicate class.

**Comment by HelloCoCooo** [comment]
@elharo Hi, maybe dependency conflicts do not only can cause runtime excetions due to missing some methods or fields, but also can lead to semantic conflicts.

When releasing a library, developers have carefully tested the method calls to their referenced libraries under their project's invocation context. 
But if the methods are forced to be invoked by another library due to dependency conflicts, host project  may change the semantic behaviors stealthily.

**Comment by elharo** [comment]
Am I misreading in thinking that both paths go through org.apache.httpcomponents? If that is true, shouldn't the fix go there so they're not publishing modules with conflicts?

**Comment by HelloCoCooo** [comment]
@elharo Thanks for your quick reply.
These two libraries (**_org.slf4j:jcl-over-slf4j_** and **_commons-logging:commons-logging_**) containing conflicting classes are introduced by **_cloud-opensource-java_**.

In **_cloud-opensource-java_** , **_httpcomponents_** depends on **_commons-logging_** rather than **_org.slf4j:jcl-over-slf4j_**, so not both of the paths go through **_httpcomponents_**.

When **_httpcomponents_** is forced to reference to the class **_org.apache.commons.logging.LogFactory_** in **_org.slf4j:jcl-over-slf4j:1.6.4_** due to dependency conflicts (first declaration wins), the code hehaviors will change.

So maybe the better solution is to reverse the declaration order in **_cloud-opensource-java_**'s pom file.

This fix will not affect other libraries or classes.

Best,
Coco

**Comment by elharo** [comment]
OK, I think I was misreading the graph. org.slf4j:jcl-over-slf4j  is coming in from Maven resolver, not from http components. That said, the Maven resolver POM is quite clear that they do want org.slf4j:jcl-over-slf4j  instead of commons logging. They explicitly exclude the latter: https://search.maven.org/artifact/org.apache.maven.resolver/maven-resolver-transport-http/1.3.3/jar

So why is commons-logging:commons-logging the right choice and org.slf4j:jcl-over-slf4j  the wrong one? I don't see a clear reason to pick one over the other.

**Comment by HelloCoCooo** [comment]
To be exact, **_commons-logging:commons-logging_** and **_org.slf4j:jcl-over-slf4j_** are all correct libraries.
**_cloud-opensource-java_** need to reference the classes defined in **_commons-logging:commons-logging_** and **_org.slf4j:jcl-over-slf4j_**.
But for the duplicate class **_org.apache.commons.logging.LogFactory_**, as shown in the dependency tree, **_cloud-opensource-java_** only expect to reference it via the path **_<org.apache.httpcomponents:httpclient:jar:4.5.6  
 -->  commons-logging:commons-logging:jar:1.2>_**  (does not expect to reference this class in **_org.slf4j:jcl-over-slf4j:1.6.4_**).

So that I means that for class **_org.apache.commons.logging.LogFactory_**,  the version included in commons-logging:commons-logging:jar is the correct one.

Unfortunately, class **_org.apache.commons.logging.LogFactory_** in **_org.slf4j:jcl-over-slf4j:1.6.4_** is actually been referenced due to class loading mechanism.

Reversing the declaring order can ensure this class in **_commons-logging:commons-logging:jar_** to be loaded using "first declaration strategy" and the fix will not affect the other classes.

Indeed, it is a work around rather than a solution.

You can also choose other repair strategies.

Thanks.

**Comment by HelloCoCooo** [comment]
By the way, I indeed found lots of issues caused by this conflicting class:

https://github.com/search?p=3&q=org.apache.commons.logging.LogFactory&type=Issues

Thanks.

**Comment by elharo** [comment]
Looks like you're using org.basepom.maven:duplicate-finder-maven-plugin. Is that correct?

**Pull request closed without merging**
