### PR TITLE
GitHub actions on Java 11

### LINKED ISSUE #1817: Pull request check in Java 11
Github Actions are easy to use and available for free. The setup does not require many configuration files.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1817 . The build passes in Java 11 now.

### CODE REVIEW

**Comment by suztomo** [comment]
Current status:

```
2020-12-01T16:48:49.2222381Z [ERROR] Failures: 
2020-12-01T16:48:49.2224911Z [ERROR]   DashboardTest.testComponent_linkageCheckResult:303 value of: trimAndCollapseWhiteSpace(...)
2020-12-01T16:48:49.2228303Z expected: 100 target classes causing linkage errors referenced from 540 source classes.
2020-12-01T16:48:49.2230385Z but was : 105 target classes causing linkage errors referenced from 562 source classes.
2020-12-01T16:48:49.2231053Z [INFO] 
2020-12-01T16:48:49.2231772Z [ERROR] Tests run: 43, Failures: 1, Errors: 0, Skipped: 0
2020-12-01T16:48:49.2232278Z [INFO] 
2020-12-01T16:48:49.2242509Z [INFO] ------------------------------------------------------------------------
2020-12-01T16:48:49.2243164Z [INFO] Reactor Summary:
2020-12-01T16:48:49.2243575Z [INFO] 
2020-12-01T16:48:49.2411850Z [INFO] Google Cloud Platform Supported Libraries 16.2.0-SNAPSHOT SUCCESS [  1.367 s]
2020-12-01T16:48:49.2413560Z [INFO] BOM Parent 1.0-SNAPSHOT ............................ SUCCESS [  0.007 s]
2020-12-01T16:48:49.2415458Z [INFO] Cloud Platform Supported Libraries Upper Bounds Check 2.0.0-SNAPSHOT SUCCESS [  8.182 s]
2020-12-01T16:48:49.2416971Z [INFO] Cloud Tools Open Source Code Hygiene Tooling 1.5.5-SNAPSHOT SUCCESS [  4.436 s]
2020-12-01T16:48:49.2418069Z [INFO] Maven Dependency Graph Analyzer 1.5.5-SNAPSHOT ..... SUCCESS [09:07 min]
2020-12-01T16:48:49.2419219Z [INFO] integration-tests 1.2.0-SNAPSHOT ................... SUCCESS [03:40 min]
2020-12-01T16:48:49.2420308Z [INFO] Cloud Tools Open Source Code Hygiene Dashboard 1.5.5-SNAPSHOT FAILURE [01:09 min]
2020-12-01T16:48:49.2421362Z [INFO] Linkage Checker Enforcer Rule 1.5.5-SNAPSHOT ....... SKIPPED
2020-12-01T16:48:49.2422290Z [INFO] Linkage Monitor 1.5.5-SNAPSHOT ..................... SKIPPED
2020-12-01T16:48:49.2423199Z [INFO] ------------------------------------------------------------------------
```

**Comment by suztomo** [comment]
Current status:

```
2020-12-02T21:51:10.3495073Z Argument(s) are different! Wanted:
2020-12-02T21:51:10.3495698Z log.error(
2020-12-02T21:51:10.3496372Z     startsWith("Linkage Checker rule found 93 errors:")
2020-12-02T21:51:10.3496981Z );
2020-12-02T21:51:10.3499523Z -> at com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRuleTest.testExecute_shouldFilterExclusionRule(LinkageCheckerRuleTest.java:463)
2020-12-02T21:51:10.3501983Z Actual invocations have different arguments:
2020-12-02T21:51:10.3502611Z log.error(
2020-12-02T21:51:10.3503210Z     "Linkage Checker rule found 98 errors:
2020-12-02T21:51:10.3503938Z Class javax.inject.Provider is not found;
2020-12-02T21:51:10.3504659Z   referenced by 21 class files
```

https://pipelines.actions.githubusercontent.com/Fu5O9i8FcLso5jbRtRss9DmEb7w3qrbqwwoyZic6OgsmkRboUU/_apis/pipelines/1/runs/60/signedlogcontent/3?urlExpires=2020-12-03T15%3A10%3A10.5222231Z&urlSigningMethod=HMACV1&urlSignature=4em%2ByToSVMTFsdPY2cEScMRbd0DyuVr4BFwtukrAmH0%3D

**Comment by suztomo** [comment]
The build succeeded.

**Comment by suztomo** [comment]
https://status.circleci.com/ shows partial outage.

> Jobs and Workflows are failing to start

**Comment by suztomo** [comment]
Removed Circle CI webhook and removed it from required checks.

**Review by elharo — APPROVED** [review]

**Pull request merged**
