### PR TITLE
Removing DependencyGraphBuilder's cache

### PR DESCRIPTION
**Pull request by suztomo**
Since resolveCompileTimeDependencies is not called multiple times, there's no point in having a cache there.

### CODE REVIEW

**Comment by elharo** [comment]
Test failures look related.

**Comment by suztomo** [comment]
Strange. I'll check them.

```
testComponent_failure - com.google.cloud.tools.opensource.dashboard.DashboardTest
java.lang.AssertionError: expected:<1> but was:<0>
	at com.google.cloud.tools.opensource.dashboard.DashboardTest.testComponent_failure(DashboardTest.java:339)

testGlobalUpperBoundUpgradeMessage - com.google.cloud.tools.opensource.dashboard.DashboardTest
com.google.common.truth.ComparisonFailureWithFacts: 
expected: 6
but was : 2
	at com.google.cloud.tools.opensource.dashboard.DashboardTest.testGlobalUpperBoundUpgradeMessage(DashboardTest.java:413)
```

**Comment by suztomo** [comment]
Investigating:

testGlobalUpperBoundUpgradeMessage


```
  private static ArtifactResults generateArtifactReport(
...
      // picks versions according to Maven rules
      DependencyGraph transitiveDependencies = artifactInfo.getTransitiveDependencies();


      Map<Artifact, Artifact> globalUpperBoundFailures = findUpperBoundsFailures(
          collectLatestVersions(globalDependencies), transitiveDependencies);
...

      templateData.put("globalUpperBoundFailures", globalUpperBoundFailures);

**Comment by suztomo** [comment]
Investigating: testComponent_failure uses grpc-google-common-protos.

## In remove_cache branch (93a47f5)

grpc-google-common-protos has 15 nodes in transitive dependencies. https://screenshot.googleplex.com/hT5wz1XL7cd.png

```
0 = {DependencyPath@3198} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile)"
1 = {DependencyPath@3199} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-stub:1.10.1 (compile)"
2 = {DependencyPath@3200} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-protobuf:1.10.1 (compile)"
3 = {DependencyPath@3201} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / com.google.api.grpc:proto-google-common-protos:1.14.0 (compile)"
4 = {DependencyPath@3202} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-stub:1.10.1 (compile) / io.grpc:grpc-core:1.10.1 (compile)"
5 = {DependencyPath@3203} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-protobuf:1.10.1 (compile) / com.google.protobuf:protobuf-java:3.5.1 (compile)"
6 = {DependencyPath@3204} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-protobuf:1.10.1 (compile) / com.google.guava:guava:19.0 (compile)"
7 = {DependencyPath@3205} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-protobuf:1.10.1 (compile) / com.google.protobuf:protobuf-java-util:3.5.1 (compile)"
8 = {DependencyPath@3206} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-protobuf:1.10.1 (compile) / io.grpc:grpc-protobuf-lite:1.10.1 (compile)"
9 = {DependencyPath@3207} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-stub:1.10.1 (compile) / io.grpc:grpc-core:1.10.1 (compile) / io.grpc:grpc-context:1.10.1 (compile)"
10 = {DependencyPath@3208} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-stub:1.10.1 (compile) / io.grpc:grpc-core:1.10.1 (compile) / com.google.code.gson:gson:2.7 (compile)"
11 = {DependencyPath@3209} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-stub:1.10.1 (compile) / io.grpc:grpc-core:1.10.1 (compile) / com.google.errorprone:error_prone_annotations:2.1.2 (compile)"
12 = {DependencyPath@3210} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-stub:1.10.1 (compile) / io.grpc:grpc-core:1.10.1 (compile) / com.google.code.findbugs:jsr305:3.0.0 (compile)"
13 = {DependencyPath@3211} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-stub:1.10.1 (compile) / io.grpc:grpc-core:1.10.1 (compile) / io.opencensus:opencensus-api:0.11.0 (compile)"
14 = {DependencyPath@3212} "com.google.api.grpc:grpc-google-common-protos:1.14.0 (compile) / io.grpc:grpc-stub:1.10.1 (compile) / io.grpc:grpc-core:1.10.1 (compile) / io.opencensus:opencensus-contrib-grpc-metrics:0.11.0 (compile)"
```

## In master

**Comment by elharo** [comment]
Unless it contains confidential information (I don't think it does) you can paste the screenshot directly into the github issue so it's accessible outside corp.

**Pull request merged**
