### PR TITLE
different prefix

### PR DESCRIPTION
**Pull request by elharo**
@chanseokoh

### CODE REVIEW

**Comment by elharo** [comment]
This is the current path:

https://pantheon.corp.google.com/storage/browser/cloud-opensource-java-dashboard/prod/cloud-opensource-java/ubuntu/periodic/3/20180713-085705/dashboard/target/dashboard/

**Comment by chanseokoh** [comment]
I don't think we can strip the `prod/cloud-opensource-java/ubuntu/periodic/3/20180713-085705/` part, which includes the Kokoro job number and the timestamp. (There might be a way, but I think that's very unlikely.)

What you stripped with the current setting is the prefix `github/cloud-opensource-java/` part after  `.../20180713-085705/`. That is, without the prefix stripping, it would have been `https://pantheon.corp.google.com/storage/browser/cloud-opensource-java-dashboard/prod/cloud-opensource-java/ubuntu/periodic/3/20180713-085705/github/cloud-opensource-java/dashboard/target/dashboard/`.

**Comment by chanseokoh** [comment]
Looking at the bucket, I guess you may want
```
strip_prefix: "github/cloud-opensource-java/dashboard/target/"
```
or
```
strip_prefix: "github/cloud-opensource-java/dashboard/target/dashboard/"
```
?

**Comment by elharo** [comment]
done

**Pull request merged**
