### PR TITLE
deps: update google-http-client to 1.39.0

### PR DESCRIPTION
**Pull request by chingor13**
Update dependencies to match next shared-dependencies release [(0.20.0)](https://github.com/googleapis/java-shared-dependencies/pull/286)

deps: update gax to 1.62.0
deps: update google-common-protos to 2.1.0

### CODE REVIEW

**Review by stephaniewang526 — APPROVED** [review]

**Review by elharo — CHANGES_REQUESTED** [review]
[ERROR] Failed to execute goal on project upper-bounds-check: Could not resolve dependencies for project com.google.cloud.tools.opensource:upper-bounds-check:pom:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.google.api:gax-httpjson:jar:0.79.0, com.google.api:gax:jar:1.62.0: Could not find artifact com.google.api:gax-httpjson:jar:0.79.0 in google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/) -> [Help 1]

**Comment by chingor13** [comment]
Hmm, that looks like the Maven mirror. The gax artifacts were published minutes ago to Maven Central.

**Review by suztomo — APPROVED** [review]

**Comment by suztomo** [comment]
I see it passed the tests.

**Review by elharo — APPROVED** [review]

**Review by elharo — COMMENTED** [review]
@chingor13 are you ready to merge this?

**Comment by chingor13** [comment]
Yeah should be good to go, note there are 3 versions being updated together.

**Pull request merged**
